# Generated by Django 6.0.7 on 2026-07-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberbullyingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullying_type', models.CharField(choices=[('insult', 'Insulting messages'), ('threat', 'Threats'), ('fake_profile', 'Fake profile'), ('private_content', 'Sharing private content'), ('exclusion', 'Exclusion from online groups'), ('rumours', 'Spreading rumours'), ('other', 'Other')], max_length=30)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('discord', 'Discord'), ('gaming', 'Online game'), ('messaging', 'Messaging application'), ('other', 'Other')], max_length=30)),
                ('age_group', models.CharField(choices=[('11-12', '11–12'), ('13-15', '13–15'), ('16-18', '16–18'), ('18+', '18+')], max_length=10)),
                ('asked_for_help', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Do not enter names or personal information.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('reports_with_help', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Report statistics',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C')], max_length=1)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
